apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-hashing-apis-v2
  namespace: monitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: cloud-hashing-apis-v2
  endpoints:
    - port: metrics